### ISSUE TITLE
Fatal error on php 8.0.1

### ISSUE THREAD

**Issue by bobe17** [elkuku/ConsoleProgressBar#3]
Hi,

I get this error on PHP 8.0.1:

> $ php -l ./vendor/elkuku/console-progressbar/src/Elkuku/Console/Helper/ConsoleProgressBar.php
PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in ./vendor/elkuku/console-progressbar/src/Elkuku/Console/Helper/ConsoleProgressBar.php on line 239

There is similar problem at line 242, 256 and 285.

**Comment by elkuku** [comment]
Package has been updated - thanks ;)
